### ISSUE TITLE
Allow configuration in yml file

### ISSUE THREAD

**Issue by Jos512** [bep/s3deploy#23]
- [x] I examined open issues in this repository.
- [x] I read the README file.
- [x] I Googled for examples of the `.s3deploy.tml` configuration file.
- [x] I Googled for how other people use s3deploy.

I like the tool and the advanced route configuration that we can do in the `.s3deploy.yml` file. But I think the tool would be easier to use from the command line when we can just type `s3deploy`, and have all other settings loaded from the config file. That makes version control of the settings possible too.

-----

Should this feature already be possible, I ask in this issue to give a quick example in the README file for reference. 

My approach at least didn't work:

```yaml
bucket: example.com
key: xcsds
region: us-east-2
secret: xdsfdsf
source: public

routes:
    - route: "^.+\\.(js|css|svg|ttf)$"
      headers:
         Cache-Control: "max-age=31536000, no-transform, public"
      gzip: true
    - route: "^.+\\.(png|jpg)$"
      headers:
         Cache-Control: "max-age=31536000, no-transform, public"
      gzip: true
    - route: "^.+\\.(html|xml|json|js)$"
      gzip: true
```

```
C:\site>s3deploy -try -config .s3deploy-us.yml
s3deploy 2.0.2, commit cc7116a41bbeed8cc9f250b48143c461a1fb4ef6, built at 2018-04-24T20:31:38Z
error: AWS bucket is required
```

---

Thanks for the time and effort put in making this tool. :slightly_smiling_face:
